all: false
force-file-write: false
formatter: goimports
log-level: info
recursive: false
require-template-schema-exists: false
template: testify
packages:
  github.com/clevertechware/todo-bun-app:
    config:
      all: true
      recursive: true
      force-file-write: true
      dir: '{{.InterfaceDir}}/mocks'
      pkgname: 'mocks'
      structname: "{{ .InterfaceName | firstUpper }}"
      filename: "{{ .InterfaceName | snakecase }}.go"
